# Generated by Django 6.0.4 on 2026-05-04 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('out_of_place', 'Out of Place'), ('spelling', 'Spelling'), ('grammar', 'Grammar'), ('langugae_mix', 'Language Mix')], max_length=50)),
                ('severity', models.CharField(choices=[('gentle', 'Gentle'), ('moderate', 'Moderate'), ('significant', 'Significant')], max_length=50)),
                ('reason', models.TextField()),
                ('applied_suggestion', models.CharField(blank=True, max_length=255, null=True)),
                ('dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlaggedWordSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replacement', models.CharField(max_length=255)),
                ('similarity_score', models.IntegerField()),
                ('flagged_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='system.flaggedword')),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WritingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('existing_text', 'Existing Text'), ('open_topic', 'Open Topic')], max_length=20)),
                ('language', models.CharField(choices=[('english', 'English'), ('filipino', 'Filipino / Tagalog')], default='english', max_length=20)),
                ('user_text', models.TextField()),
                ('identified_topic', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.passage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flaggedword',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_words', to='system.writingsession'),
        ),
    ]
