# Generated by Django 6.0.4 on 2026-05-11 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_flaggedword_flaggedwordsuggestion_passage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedword',
            name='type',
            field=models.CharField(choices=[('out_of_place', 'Out of Place'), ('spelling', 'Spelling'), ('grammar', 'Grammar'), ('language_mix', 'Language Mix')], max_length=50),
        ),
        migrations.AlterField(
            model_name='passage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField()),
                ('words_presented', models.JSONField(default=list)),
                ('hearts_remaining', models.IntegerField(default=5)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSessionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt1_word_ids', models.JSONField(default=list)),
                ('attempt2_word_ids', models.JSONField(default=list)),
                ('current_attempt', models.IntegerField(default=1)),
                ('current_index', models.IntegerField(default=0)),
                ('hearts', models.IntegerField(default=5)),
                ('attempt1_results', models.JSONField(default=dict)),
                ('attempt2_results', models.JSONField(default=dict)),
                ('is_over', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_session', to=settings.AUTH_USER_MODEL)),
                ('session_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='system.sessionlog')),
            ],
        ),
        migrations.CreateModel(
            name='WordState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('augmentation_level', models.IntegerField(default=0)),
                ('initial_augmentation_level', models.IntegerField(default=0)),
                ('augmentation_gap', models.IntegerField(default=0)),
                ('severity_score', models.IntegerField(default=0)),
                ('severity_threshold', models.IntegerField(default=3)),
                ('frequency_weight', models.FloatField(default=1.0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('streak_correct', models.IntegerField(default=0)),
                ('streak_miss', models.IntegerField(default=0)),
                ('attempt_history', models.JSONField(default=list)),
                ('sessions_seen', models.IntegerField(default=0)),
                ('sessions_since_last_escalation', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('regressed', 'REGRESSED'), ('maintained', 'MAINTAINED'), ('escalated', 'ESCALATED'), ('pending', 'PENDING'), ('flagged', 'FLAGGED')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_words', to='system.sessionlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-frequency_weight', '-severity_score', 'word'],
                'unique_together': {('user', 'word')},
            },
        ),
        migrations.CreateModel(
            name='WordFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_tag', models.CharField(choices=[('NOUN', 'Noun'), ('VERB', 'Verb'), ('ADJ', 'Adjective'), ('ADV', 'Adverb'), ('PRON', 'Pronoun'), ('DET', 'Determiner'), ('ADP', 'Adposition'), ('CONJ', 'Conjunction'), ('NUM', 'Numeral'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('syllable_count', models.IntegerField(default=1)),
                ('morphological_pattern', models.CharField(blank=True, max_length=50)),
                ('bert_embedding', models.JSONField(default=list)),
                ('rule_features', models.JSONField(default=dict)),
                ('word_state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='system.wordstate')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1)),
                ('correct', models.BooleanField()),
                ('whisper_transcript', models.CharField(blank=True, max_length=200)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('augmentation_level_at_attempt', models.IntegerField(default=0)),
                ('initial_augmentation_level', models.IntegerField(default=0)),
                ('augmentation_gap_at_attempt', models.IntegerField(default=0)),
                ('severity_at_attempt', models.IntegerField(default=0)),
                ('feature_vector', models.JSONField(default=dict)),
                ('label', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='system.sessionlog')),
                ('word_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_logs', to='system.wordstate')),
            ],
        ),
    ]
